author:
  name: Ousmane Dao
  email: ousmanedao17@yahoo.fr
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:ousmane.dao@york.ac.uk"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0002-7040-5770"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/ousmane-dao-979315131/"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/ousmanebahdao"
    - label: "ResearchGate"
      icon: "ai ai-researchgate"
      url: "https://www.researchgate.net/profile/Ousmane-Dao"
