title: "Ousmane Dao"
email: ousmanedao17@yahoo.fr
description: >-
  Postdoctoral researcher in plant biology working on the resilience of photosynthetic organisms at the University of York.

baseurl: "" # Leave empty for GitHub Pages root
url: "https://ousmanedao.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Collections for custom pages
collections:
  publications:
    output: true
    permalink: /publication/:path/
  teaching:
    output: true
    permalink: /teaching/:path/
  talks:
    output: true
    permalink: /talks/:path/

# Author details (used on homepage & sidebar)
author:
  name: Ousmane Dao
  email: ousmanedao17@yahoo.fr
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:ousmane.dao@york.ac.uk"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0002-7040-5770"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/ousmane-dao-979315131/"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/ousmanebahdao"
    - label: "ResearchGate"
      icon: "ai ai-researchgate"
      url: "https://www.researchgate.net/profile/Ousmane-Dao"

# Permalinks for blog and posts
permalink: pretty

# Optional: site logo (place logo file in /images)
# logo: "/images/ousmanedao.jpg"

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXXX-X
